blank_issues_enabled: false
contact_links:
  - name: Question or general discussion
    url: https://github.com/quinnuk/LoopClip/discussions
    about: For questions or general chat that aren't a bug report or feature request.
